// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiredemo

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

// InitializeUserController 初始化用户控制器
func InitializeUserController() (*UserController, error) {
	database, err := NewDatabase()
	if err != nil {
		return nil, err
	}
	userRepository := NewUserRepository(database)
	userService := NewUserService(userRepository)
	userController := NewUserController(userService)
	return userController, nil
}
